services:
  odoo_db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:5432"
    tty: true

  odoo_web:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
      args:
        - ODOO_VERSION=${ODOO_VERSION}
        - ENTERPRISE_ADDONS_PATH=${ENTERPRISE_ADDONS_PATH}
        - DESIGN_THEMES_ADDONS_PATH=${DESIGN_THEMES_ADDONS_PATH}
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
      - "8888:8888"
    volumes:
      - odoo_web_data:/var/lib/odoo
    environment:
      - HOST=${DB_HOST}
      - PORT=5432
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    command: /usr/bin/python3 -m debugpy --listen 0.0.0.0:8888 /usr/bin/odoo --config=${ODOO_RC}
    tty: true

volumes:
  odoo_web_data:
  odoo_db_data:
networks:
  default:
